â–¿ Result<RemoteNodeConnection, DataError>
  - failure: DataError.noSavedData
